import mongoose from "mongoose";

const taskSchema = new mongoose.Schema(
    {
        
        user: { 
            type: mongoose.Schema.Types.ObjectId, 
            ref: "User", 
            required: true 
        },
        
       
        title: {
            type: String,
            required: true,
            trim: true
        },
        
        description: {
            type: String,
            trim: true
        },
        
        category: {
            type: String,
            enum: ["Wellness", "Mindfulness", "Activity", "Social", "Sleep", "Nutrition"],
            default: "Wellness"
        },

        isCompleted: {
            type: Boolean,
            default: false
        },
        
        assignedDate: {
            type: Date,
            default: Date.now,
        },

        expiresAt: {
            type: Date,
            required: true
        },

        isAutoGenerated: {
            type: Boolean,
            default: false
        },

        priority: {
            type: String,
            enum: ["low", "medium", "high"],
            default: "medium"
        }
    },
    { 
        timestamps: true 
    }
);

// Index for automatic cleanup of expired tasks
taskSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

export default mongoose.model("Task", taskSchema);